apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-sync-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "watch", "create", "patch", "delete"]